/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: logproto.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "logproto.pb-c.h"
void   logproto__push_request__init
                     (Logproto__PushRequest         *message)
{
  static const Logproto__PushRequest init_value = LOGPROTO__PUSH_REQUEST__INIT;
  *message = init_value;
}
size_t logproto__push_request__get_packed_size
                     (const Logproto__PushRequest *message)
{
  assert(message->base.descriptor == &logproto__push_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t logproto__push_request__pack
                     (const Logproto__PushRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &logproto__push_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t logproto__push_request__pack_to_buffer
                     (const Logproto__PushRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &logproto__push_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Logproto__PushRequest *
       logproto__push_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Logproto__PushRequest *)
     protobuf_c_message_unpack (&logproto__push_request__descriptor,
                                allocator, len, data);
}
void   logproto__push_request__free_unpacked
                     (Logproto__PushRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &logproto__push_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   logproto__push_response__init
                     (Logproto__PushResponse         *message)
{
  static const Logproto__PushResponse init_value = LOGPROTO__PUSH_RESPONSE__INIT;
  *message = init_value;
}
size_t logproto__push_response__get_packed_size
                     (const Logproto__PushResponse *message)
{
  assert(message->base.descriptor == &logproto__push_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t logproto__push_response__pack
                     (const Logproto__PushResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &logproto__push_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t logproto__push_response__pack_to_buffer
                     (const Logproto__PushResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &logproto__push_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Logproto__PushResponse *
       logproto__push_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Logproto__PushResponse *)
     protobuf_c_message_unpack (&logproto__push_response__descriptor,
                                allocator, len, data);
}
void   logproto__push_response__free_unpacked
                     (Logproto__PushResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &logproto__push_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   logproto__query_request__init
                     (Logproto__QueryRequest         *message)
{
  static const Logproto__QueryRequest init_value = LOGPROTO__QUERY_REQUEST__INIT;
  *message = init_value;
}
size_t logproto__query_request__get_packed_size
                     (const Logproto__QueryRequest *message)
{
  assert(message->base.descriptor == &logproto__query_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t logproto__query_request__pack
                     (const Logproto__QueryRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &logproto__query_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t logproto__query_request__pack_to_buffer
                     (const Logproto__QueryRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &logproto__query_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Logproto__QueryRequest *
       logproto__query_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Logproto__QueryRequest *)
     protobuf_c_message_unpack (&logproto__query_request__descriptor,
                                allocator, len, data);
}
void   logproto__query_request__free_unpacked
                     (Logproto__QueryRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &logproto__query_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   logproto__query_response__init
                     (Logproto__QueryResponse         *message)
{
  static const Logproto__QueryResponse init_value = LOGPROTO__QUERY_RESPONSE__INIT;
  *message = init_value;
}
size_t logproto__query_response__get_packed_size
                     (const Logproto__QueryResponse *message)
{
  assert(message->base.descriptor == &logproto__query_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t logproto__query_response__pack
                     (const Logproto__QueryResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &logproto__query_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t logproto__query_response__pack_to_buffer
                     (const Logproto__QueryResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &logproto__query_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Logproto__QueryResponse *
       logproto__query_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Logproto__QueryResponse *)
     protobuf_c_message_unpack (&logproto__query_response__descriptor,
                                allocator, len, data);
}
void   logproto__query_response__free_unpacked
                     (Logproto__QueryResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &logproto__query_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   logproto__label_request__init
                     (Logproto__LabelRequest         *message)
{
  static const Logproto__LabelRequest init_value = LOGPROTO__LABEL_REQUEST__INIT;
  *message = init_value;
}
size_t logproto__label_request__get_packed_size
                     (const Logproto__LabelRequest *message)
{
  assert(message->base.descriptor == &logproto__label_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t logproto__label_request__pack
                     (const Logproto__LabelRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &logproto__label_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t logproto__label_request__pack_to_buffer
                     (const Logproto__LabelRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &logproto__label_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Logproto__LabelRequest *
       logproto__label_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Logproto__LabelRequest *)
     protobuf_c_message_unpack (&logproto__label_request__descriptor,
                                allocator, len, data);
}
void   logproto__label_request__free_unpacked
                     (Logproto__LabelRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &logproto__label_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   logproto__label_response__init
                     (Logproto__LabelResponse         *message)
{
  static const Logproto__LabelResponse init_value = LOGPROTO__LABEL_RESPONSE__INIT;
  *message = init_value;
}
size_t logproto__label_response__get_packed_size
                     (const Logproto__LabelResponse *message)
{
  assert(message->base.descriptor == &logproto__label_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t logproto__label_response__pack
                     (const Logproto__LabelResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &logproto__label_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t logproto__label_response__pack_to_buffer
                     (const Logproto__LabelResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &logproto__label_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Logproto__LabelResponse *
       logproto__label_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Logproto__LabelResponse *)
     protobuf_c_message_unpack (&logproto__label_response__descriptor,
                                allocator, len, data);
}
void   logproto__label_response__free_unpacked
                     (Logproto__LabelResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &logproto__label_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   logproto__stream__init
                     (Logproto__Stream         *message)
{
  static const Logproto__Stream init_value = LOGPROTO__STREAM__INIT;
  *message = init_value;
}
size_t logproto__stream__get_packed_size
                     (const Logproto__Stream *message)
{
  assert(message->base.descriptor == &logproto__stream__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t logproto__stream__pack
                     (const Logproto__Stream *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &logproto__stream__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t logproto__stream__pack_to_buffer
                     (const Logproto__Stream *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &logproto__stream__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Logproto__Stream *
       logproto__stream__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Logproto__Stream *)
     protobuf_c_message_unpack (&logproto__stream__descriptor,
                                allocator, len, data);
}
void   logproto__stream__free_unpacked
                     (Logproto__Stream *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &logproto__stream__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   logproto__entry__init
                     (Logproto__Entry         *message)
{
  static const Logproto__Entry init_value = LOGPROTO__ENTRY__INIT;
  *message = init_value;
}
size_t logproto__entry__get_packed_size
                     (const Logproto__Entry *message)
{
  assert(message->base.descriptor == &logproto__entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t logproto__entry__pack
                     (const Logproto__Entry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &logproto__entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t logproto__entry__pack_to_buffer
                     (const Logproto__Entry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &logproto__entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Logproto__Entry *
       logproto__entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Logproto__Entry *)
     protobuf_c_message_unpack (&logproto__entry__descriptor,
                                allocator, len, data);
}
void   logproto__entry__free_unpacked
                     (Logproto__Entry *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &logproto__entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor logproto__push_request__field_descriptors[1] =
{
  {
    "streams",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Logproto__PushRequest, n_streams),
    offsetof(Logproto__PushRequest, streams),
    &logproto__stream__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned logproto__push_request__field_indices_by_name[] = {
  0,   /* field[0] = streams */
};
static const ProtobufCIntRange logproto__push_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor logproto__push_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "logproto.PushRequest",
  "PushRequest",
  "Logproto__PushRequest",
  "logproto",
  sizeof(Logproto__PushRequest),
  1,
  logproto__push_request__field_descriptors,
  logproto__push_request__field_indices_by_name,
  1,  logproto__push_request__number_ranges,
  (ProtobufCMessageInit) logproto__push_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define logproto__push_response__field_descriptors NULL
#define logproto__push_response__field_indices_by_name NULL
#define logproto__push_response__number_ranges NULL
const ProtobufCMessageDescriptor logproto__push_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "logproto.PushResponse",
  "PushResponse",
  "Logproto__PushResponse",
  "logproto",
  sizeof(Logproto__PushResponse),
  0,
  logproto__push_response__field_descriptors,
  logproto__push_response__field_indices_by_name,
  0,  logproto__push_response__number_ranges,
  (ProtobufCMessageInit) logproto__push_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor logproto__query_request__field_descriptors[6] =
{
  {
    "query",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Logproto__QueryRequest, query),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "limit",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Logproto__QueryRequest, limit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Logproto__QueryRequest, start),
    &google__protobuf__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Logproto__QueryRequest, end),
    &google__protobuf__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "direction",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Logproto__QueryRequest, direction),
    &logproto__direction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "regex",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Logproto__QueryRequest, regex),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned logproto__query_request__field_indices_by_name[] = {
  4,   /* field[4] = direction */
  3,   /* field[3] = end */
  1,   /* field[1] = limit */
  0,   /* field[0] = query */
  5,   /* field[5] = regex */
  2,   /* field[2] = start */
};
static const ProtobufCIntRange logproto__query_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor logproto__query_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "logproto.QueryRequest",
  "QueryRequest",
  "Logproto__QueryRequest",
  "logproto",
  sizeof(Logproto__QueryRequest),
  6,
  logproto__query_request__field_descriptors,
  logproto__query_request__field_indices_by_name,
  1,  logproto__query_request__number_ranges,
  (ProtobufCMessageInit) logproto__query_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor logproto__query_response__field_descriptors[1] =
{
  {
    "streams",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Logproto__QueryResponse, n_streams),
    offsetof(Logproto__QueryResponse, streams),
    &logproto__stream__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned logproto__query_response__field_indices_by_name[] = {
  0,   /* field[0] = streams */
};
static const ProtobufCIntRange logproto__query_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor logproto__query_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "logproto.QueryResponse",
  "QueryResponse",
  "Logproto__QueryResponse",
  "logproto",
  sizeof(Logproto__QueryResponse),
  1,
  logproto__query_response__field_descriptors,
  logproto__query_response__field_indices_by_name,
  1,  logproto__query_response__number_ranges,
  (ProtobufCMessageInit) logproto__query_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor logproto__label_request__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Logproto__LabelRequest, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "values",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Logproto__LabelRequest, values),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned logproto__label_request__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = values */
};
static const ProtobufCIntRange logproto__label_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor logproto__label_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "logproto.LabelRequest",
  "LabelRequest",
  "Logproto__LabelRequest",
  "logproto",
  sizeof(Logproto__LabelRequest),
  2,
  logproto__label_request__field_descriptors,
  logproto__label_request__field_indices_by_name,
  1,  logproto__label_request__number_ranges,
  (ProtobufCMessageInit) logproto__label_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor logproto__label_response__field_descriptors[1] =
{
  {
    "values",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Logproto__LabelResponse, n_values),
    offsetof(Logproto__LabelResponse, values),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned logproto__label_response__field_indices_by_name[] = {
  0,   /* field[0] = values */
};
static const ProtobufCIntRange logproto__label_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor logproto__label_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "logproto.LabelResponse",
  "LabelResponse",
  "Logproto__LabelResponse",
  "logproto",
  sizeof(Logproto__LabelResponse),
  1,
  logproto__label_response__field_descriptors,
  logproto__label_response__field_indices_by_name,
  1,  logproto__label_response__number_ranges,
  (ProtobufCMessageInit) logproto__label_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor logproto__stream__field_descriptors[2] =
{
  {
    "labels",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Logproto__Stream, labels),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "entries",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Logproto__Stream, n_entries),
    offsetof(Logproto__Stream, entries),
    &logproto__entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned logproto__stream__field_indices_by_name[] = {
  1,   /* field[1] = entries */
  0,   /* field[0] = labels */
};
static const ProtobufCIntRange logproto__stream__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor logproto__stream__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "logproto.Stream",
  "Stream",
  "Logproto__Stream",
  "logproto",
  sizeof(Logproto__Stream),
  2,
  logproto__stream__field_descriptors,
  logproto__stream__field_indices_by_name,
  1,  logproto__stream__number_ranges,
  (ProtobufCMessageInit) logproto__stream__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor logproto__entry__field_descriptors[2] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Logproto__Entry, timestamp),
    &google__protobuf__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "line",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Logproto__Entry, line),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned logproto__entry__field_indices_by_name[] = {
  1,   /* field[1] = line */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange logproto__entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor logproto__entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "logproto.Entry",
  "Entry",
  "Logproto__Entry",
  "logproto",
  sizeof(Logproto__Entry),
  2,
  logproto__entry__field_descriptors,
  logproto__entry__field_indices_by_name,
  1,  logproto__entry__number_ranges,
  (ProtobufCMessageInit) logproto__entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue logproto__direction__enum_values_by_number[2] =
{
  { "FORWARD", "LOGPROTO__DIRECTION__FORWARD", 0 },
  { "BACKWARD", "LOGPROTO__DIRECTION__BACKWARD", 1 },
};
static const ProtobufCIntRange logproto__direction__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex logproto__direction__enum_values_by_name[2] =
{
  { "BACKWARD", 1 },
  { "FORWARD", 0 },
};
const ProtobufCEnumDescriptor logproto__direction__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "logproto.Direction",
  "Direction",
  "Logproto__Direction",
  "logproto",
  2,
  logproto__direction__enum_values_by_number,
  2,
  logproto__direction__enum_values_by_name,
  1,
  logproto__direction__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCMethodDescriptor logproto__pusher__method_descriptors[1] =
{
  { "Push", &logproto__push_request__descriptor, &logproto__push_response__descriptor },
};
const unsigned logproto__pusher__method_indices_by_name[] = {
  0         /* Push */
};
const ProtobufCServiceDescriptor logproto__pusher__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "logproto.Pusher",
  "Pusher",
  "Logproto__Pusher",
  "logproto",
  1,
  logproto__pusher__method_descriptors,
  logproto__pusher__method_indices_by_name
};
void logproto__pusher__push(ProtobufCService *service,
                            const Logproto__PushRequest *input,
                            Logproto__PushResponse_Closure closure,
                            void *closure_data)
{
  assert(service->descriptor == &logproto__pusher__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void logproto__pusher__init (Logproto__Pusher_Service *service,
                             Logproto__Pusher_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &logproto__pusher__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
static const ProtobufCMethodDescriptor logproto__querier__method_descriptors[2] =
{
  { "Query", &logproto__query_request__descriptor, &logproto__query_response__descriptor },
  { "Label", &logproto__label_request__descriptor, &logproto__label_response__descriptor },
};
const unsigned logproto__querier__method_indices_by_name[] = {
  1,        /* Label */
  0         /* Query */
};
const ProtobufCServiceDescriptor logproto__querier__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "logproto.Querier",
  "Querier",
  "Logproto__Querier",
  "logproto",
  2,
  logproto__querier__method_descriptors,
  logproto__querier__method_indices_by_name
};
void logproto__querier__query(ProtobufCService *service,
                              const Logproto__QueryRequest *input,
                              Logproto__QueryResponse_Closure closure,
                              void *closure_data)
{
  assert(service->descriptor == &logproto__querier__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void logproto__querier__label(ProtobufCService *service,
                              const Logproto__LabelRequest *input,
                              Logproto__LabelResponse_Closure closure,
                              void *closure_data)
{
  assert(service->descriptor == &logproto__querier__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void logproto__querier__init (Logproto__Querier_Service *service,
                              Logproto__Querier_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &logproto__querier__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
